### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by CHSLAM** [yxianzhe/DynaProp#1]
DynaProp-main/include/Conversion.h:13:10: fatal error: Python.h: 没有那个文件或目录
 #include <Python.h>

**Comment by yxianzhe** [comment]
> DynaProp-main/include/Conversion.h:13:10: fatal error: Python.h: 没有那个文件或目录 #include <Python.h>

First make sure you have Python2.7 installed on your machine, and then you need to verify the python include dir to the place where Python is installed in CMakeLists.txt.

set( PYTHON_INCLUDE_DIR /home/yxz/anaconda3/envs/dyna/include/python2.7 )
set( PYTHON_LIBRARY /home/yxz/anaconda3/envs/dyna/lib/libpython2.7.so) @CHSLAM

**Comment by CHSLAM** [comment]
> > DynaProp-main/include/Conversion.h:13:10: fatal error: Python.h: 没有那个文件或目录 #include <Python.h>
> 
> First make sure you have Python2.7 installed on your machine, and then you need to verify the python include dir to the place where Python is installed in CMakeLists.txt.
> 
> set( PYTHON_INCLUDE_DIR /home/yxz/anaconda3/envs/dyna/include/python2.7 ) set( PYTHON_LIBRARY /home/yxz/anaconda3/envs/dyna/lib/libpython2.7.so) @CHSLAM

DynaProp-main/include/Conversion.h:17:10: fatal error: ndarrayobject.h: 没有那个文件或目录

**Comment by CHSLAM** [comment]
> > DynaProp-main/include/Conversion.h:13:10: fatal error: Python.h: 没有那个文件或目录 #include <Python.h>
> 
> First make sure you have Python2.7 installed on your machine, and then you need to verify the python include dir to the place where Python is installed in CMakeLists.txt.
> 
> set( PYTHON_INCLUDE_DIR /home/yxz/anaconda3/envs/dyna/include/python2.7 ) set( PYTHON_LIBRARY /home/yxz/anaconda3/envs/dyna/lib/libpython2.7.so) @CHSLAM

when I run it
Loading Mask R-CNN. This could take a while...
Importing Mask R-CNN Settings...
Segmentation fault (core dumped)

**Comment by yxianzhe** [comment]
> > > DynaProp-main/include/Conversion.h:13:10: fatal error: Python.h: 没有那个文件或目录 #include <Python.h>
> > 
> > 
> > First make sure you have Python2.7 installed on your machine, and then you need to verify the python include dir to the place where Python is installed in CMakeLists.txt.
> > set( PYTHON_INCLUDE_DIR /home/yxz/anaconda3/envs/dyna/include/python2.7 ) set( PYTHON_LIBRARY /home/yxz/anaconda3/envs/dyna/lib/libpython2.7.so) @CHSLAM
> 
> when I run it Loading Mask R-CNN. This could take a while... Importing Mask R-CNN Settings... Segmentation fault (core dumped)

Segmentation fault can be caused by many reasons, I guess you did not fix your python environment right.
I suggest you first run DynaSLAM on [https://github.com/BertaBescos/DynaSLAM](url). It should be easier and there are more details about how to deal with the errors. 
If you run DynaSLAM successfully, you will be able to run DynaProp without problems.
